# Config file for automatic testing at travis-ci.org
dist: bionic
language: python
python:
  - 3.7
  - 3.6
  - 3.5

matrix:
  include:
    - os: osx
      language: generic

# Command to install dependencies
addons:
  apt:
    packages:
      - pandoc
  homebrew:
    packages:
      - pandoc
install: pip install -U tox-travis codecov

# Command to run tests
script: tox

after_success: codecov

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      branch: stable
      python: 3.7
